/*! PM-Core (c) 2026 Paul Hsu. All Rights Reserved. Proprietary — see LICENSE. */
(()=>{const MV=App.MergeView={active:false,picked:[],stations:[],stationOf:{},asOf:null};const fmtTime=iso=>{const d=new Date(iso);if(isNaN(d.getTime()))return String(iso||"");const p=n=>String(n).padStart(2,"0");return p(d.getMonth()+1)+"/"+p(d.getDate())+" "+p(d.getHours())+":"+p(d.getMinutes())};App._mvFmtTime=fmtTime;MV.mergePacks=function(packs){const byStation={};(packs||[]).forEach(pk=>{const k=pk.station||"未命名站台";if(!byStation[k]||String(pk.exported||"")>String(byStation[k].exported||""))byStation[k]=Object.assign({},pk,{station:k})});const use=Object.values(byStation);const own={};use.forEach(pk=>((pk.data||{}).projects||[]).forEach(p=>{if(!own[p.id]||String(pk.exported||"")>String(own[p.id].exported||""))own[p.id]={station:pk.station,exported:pk.exported,proj:p}}));const projects=Object.values(own).map(o=>o.proj);const stationOf={};Object.keys(own).forEach(id=>{stationOf[id]=own[id].station});const tasks=[];use.forEach(pk=>((pk.data||{}).tasks||[]).forEach(t=>{if(t.project){if((own[t.project]||{}).station===pk.station)tasks.push(t)}else tasks.push(t)}));const asOf=use.map(pk=>pk.exported).filter(Boolean).sort()[0]||null;return{projects,tasks,stationOf,asOf,stations:use.map(pk=>({station:pk.station,exported:pk.exported})),dupDropped:(packs||[]).length-use.length}};App.openMergeView=function(){MV.picked=[];App.openModal({title:"👥 彙整檢視——選擇各站台的備份檔",body:`<div class="mv-bd">
        <div class="mv-drop" onclick="document.getElementById('mv-file').click()"
          ondragover="event.preventDefault();this.classList.add('over')" ondragleave="this.classList.remove('over')"
          ondrop="event.preventDefault();this.classList.remove('over');App._mvAddFiles(event.dataTransfer.files)">把各站台匯出的備份檔（JSON）拖進這裡，或<b>點這裡選擇檔案</b>（可一次多個）</div>
        <input type="file" id="mv-file" accept=".json" multiple style="display:none" onchange="App._mvOnFiles(this)">
        <div id="mv-list" class="mv-list"></div>
        <div class="mv-hint">只在這台電腦的記憶體合併，<b>不會改動任何人的資料</b>；按「取消」不進行彙整。進入後畫面頂端有「離開彙整」可隨時回到自己的資料。</div>
      </div>`,footer:`<button class="rg-btn ghost" onclick="App.closeModal()">取消</button>
        <button class="rg-btn primary" id="mv-start" disabled onclick="App._mvStart()">開始彙整（唯讀）</button>`})};App._mvOnFiles=function(input){const fs=input.files;App._mvAddFiles(fs);input.value=""};App._mvAddFiles=function(fileList){const files=Array.from(fileList||[]).filter(f=>/\.json$/i.test(f.name));if((fileList||[]).length&&!files.length)return U.toast("請選 .json 備份檔（各站台從「設定 → 本機資料」匯出的那種）","warning");let left=files.length;if(!left)return;files.forEach(f=>{const rd=new FileReader;rd.onload=e=>{try{const obj=JSON.parse(e.target.result);if(!obj.DATA||!Array.isArray(obj.DATA.projects)||!Array.isArray(obj.DATA.tasks))throw new Error("檔案格式錯誤（缺 DATA.projects/tasks）");MV.picked.push({station:String(obj.stationName||"").trim()||f.name.replace(/\.json$/i,""),exported:obj.exported||"",data:obj.DATA,fname:f.name})}catch(err){U.toast("「"+f.name+"」讀不進來："+(err.message||err),"error")}if(!--left)App._mvRenderList()};rd.readAsText(f)})};App._mvRenderList=function(){const el=document.getElementById("mv-list");if(!el)return;const newest={};MV.picked.forEach(pk=>{if(!newest[pk.station]||String(pk.exported)>String(newest[pk.station]))newest[pk.station]=pk.exported});const DAY=864e5;el.innerHTML=MV.picked.map((pk,i)=>{const age=pk.exported?Math.floor((Date.now()-new Date(pk.exported).getTime())/DAY):null;const stale=age!=null&&age>=3;const dup=String(pk.exported)!==String(newest[pk.station]);const warn=dup?"同站台選了較新的另一份——這份會被略過。":stale?"⚠ "+age+" 天前的舊檔——會照用，但數字可能過時，建議請站台重新匯出。":"";return`<div class="mv-file${stale||dup?" warn":""}">
        <div class="mv-file-st">${dup?"↺":stale?"⚠":"✓"}</div>
        <div class="mv-file-nm">${U.esc(pk.station)}</div>
        <div class="mv-file-cnt">${(pk.data.projects||[]).length} 專案<br>${(pk.data.tasks||[]).length} 任務</div>
        <button class="mv-file-rm" onclick="App._mvRemove(${i})" title="移除這份檔案">✕</button>
        <div class="mv-file-meta">${U.esc(pk.fname)} · 匯出於 ${pk.exported?U.esc(fmtTime(pk.exported)):"（無時間戳）"}</div>
        ${warn?`<div class="mv-file-wtxt">${warn}</div>`:""}</div>`}).join("");const btn=document.getElementById("mv-start");if(btn)btn.disabled=!MV.picked.length};App._mvRemove=function(i){MV.picked.splice(i,1);App._mvRenderList()};App._mvStart=function(){if(!MV.picked.length)return;const m=MV.mergePacks(MV.picked);DATA.projects=m.projects;DATA.tasks=m.tasks;MV.active=true;MV.stationOf=m.stationOf;MV.asOf=m.asOf;MV.stations=m.stations;document.body.classList.add("viewonly","merge-view");const bn=document.createElement("div");bn.className="mv-banner";bn.id="mvBanner";bn.innerHTML=`<i class="ti ti-users-group"></i> 彙整檢視中 <span class="mv-ro">唯讀</span>
      <span class="mv-info">${MV.stations.length} 個站台 · ${m.projects.length} 專案 · 資料截至 ${MV.asOf?U.esc(fmtTime(MV.asOf)):"—"}${MV.asOf&&MV.stations.length>1?"（最舊檔）":""}</span>
      <button class="mv-leave" onclick="App._mvExit()">離開彙整</button>`;document.body.appendChild(bn);App.closeModal();App.showPage("portfolio");App.refreshAll();U.toast("已進入彙整檢視（唯讀）——離開後你的資料原封不動")};App._mvExit=function(){location.reload()};const mvAvail=typeof OFFLINE_BUILD!=="undefined"&&OFFLINE_BUILD||typeof isLocalDev!=="undefined"&&isLocalDev;if(mvAvail){App.registerModule({id:"mergeview",cat:"manage",title:"主管彙整檢視",icon:"ti-users-group",desc:"把各站台匯出的備份檔合併成全公司唯讀總覽——進度、負荷、熱點一次看。",action:"openMergeView"});const btn=document.getElementById("mvEntry");if(btn)btn.style.display=""}})();
