/*! PM-Core (c) 2026 Paul Hsu. All Rights Reserved. Proprietary — see LICENSE. */
App.PRED_RELATIONS=[{code:"FS",label:"等它完成後，本任務才開始（最常用）"},{code:"SS",label:"跟它同一天開始"},{code:"FF",label:"跟它同一天完成"},{code:"SF",label:"它開始後，本任務才能完成"}];App.predCandidates=function(projId,selfId,currentStage,selfVariant){const norm=normStage;const stages=App.getProjectStages(projId);const nameToIdx={};let k=0;stages.forEach(s=>{if(!(s.name in nameToIdx))nameToIdx[s.name]=k++});const idxOf=stage=>norm(stage)in nameToIdx?nameToIdx[norm(stage)]:stages.length;const S=idxOf(currentStage);const ordered=App.orderedProjectTasks(projId);const selfPos=selfId?ordered.findIndex(t=>t.id===selfId):-1;const selfBefore=selfPos<0?Infinity:selfPos;return ordered.map((t,pos)=>({t,pos})).filter(({t,pos})=>{if(t.id===selfId)return false;if(t.measureType==="hours")return false;if((t.variant||null)!==(selfVariant||null))return false;const d=S-idxOf(t.stage);if(d===0)return pos<selfBefore;if(d===1||d===2)return true;return false}).map(({t,pos})=>({id:t.id,seq:pos+1,name:t.name||"",stage:norm(t.stage),stageIdx:idxOf(t.stage)}))};App._predRowHtml=function(pred,candidates){const cands=candidates||App._predCands||[];const depId=pred?String(pred.dep):"";const type=pred?pred.type:"FS";const lag=pred?pred.lag:0;let optsHtml=`<option value="">（不設前置）</option>`;const byIdx={},order=[];cands.forEach(c=>{if(!(c.stageIdx in byIdx)){byIdx[c.stageIdx]={name:c.stage,items:[]};order.push(c.stageIdx)}byIdx[c.stageIdx].items.push(c)});order.sort((a,b)=>a-b);order.forEach(idx=>{const g=byIdx[idx];optsHtml+=`<optgroup label="${U.esc(g.name)}">`+g.items.map(c=>`<option value="${U.esc(c.id)}"${c.id===depId?" selected":""}>${U.esc(c.seq+" · "+c.name)}</option>`).join("")+`</optgroup>`});if(depId&&!cands.some(c=>c.id===depId)){const to=(DATA.tasks||[]).find(t=>t.id===depId);const label=to?App._seqOf(depId)+" · "+(to.name||""):depId;optsHtml+=`<optgroup label="（目前範圍外）"><option value="${U.esc(depId)}" selected>${U.esc(label)}（範圍外）</option></optgroup>`}const rels=App.PRED_RELATIONS.map(r=>`<option value="${r.code}" ${type===r.code?"selected":""}>${U.esc(r.label)}</option>`).join("");return`
      <div class="pred-row">
        <div class="pred-field">
          <label class="pred-field-label">🔗 要接在這個任務之後</label>
          <div class="pred-field-line">
            <select class="pred-search">${optsHtml}</select>
            <button type="button" class="pred-del" onclick="App.removePredRow(this)" title="刪除這條前置">✕</button>
          </div>
        </div>
        <div class="pred-field">
          <label class="pred-field-label">🔀 兩者的銜接方式</label>
          <select class="pred-rel">${rels}</select>
        </div>
        <div class="pred-field">
          <label class="pred-field-label">⏳ 中間留幾天緩衝</label>
          <input type="number" class="pred-lag" value="${lag}" step="1" min="0">
          <div class="field-hint">前置完成後想多等幾天再開始（等材料、簽核）才需要填，不需要則維持 0。</div>
        </div>
      </div>`};App.buildPredListHtml=function(t){const cands=App.predCandidates(t.project,t.id,t.stage,t.variant);App._predCands=cands;App._predProj=t.project;App._predSelfId=t.id;App._predVariant=t.variant;const preds=parsePredecessors(t.predecessor);const rows=preds.length?preds.map(p=>App._predRowHtml(p,cands)).join(""):App._predRowHtml(null,cands);return`
      <div class="field-hint pred-intro">設定這個任務接在哪個任務之後，系統會自動排好開始日期。</div>
      <div id="tf-pred-list">${rows}</div>
      <button type="button" class="pred-add" onclick="App.addPredRow()">＋ 加一條前置</button>
      <div class="tip pred-example">想成『這件事要排在誰後面』。例如本任務要等『#16 模具開發』做完、再隔 2 天材料到位才動工 → 選 #16、選『完成後才開始』、緩衝填 2。</div>`};App.serializePredecessors=function(){const rows=Array.from(document.querySelectorAll("#tf-pred-list .pred-row"));const parts=[];for(const row of rows){const sel=row.querySelector(".pred-search");const id=sel?(sel.value||"").trim():"";if(!id)continue;const type=(row.querySelector(".pred-rel")||{}).value||"FS";const lagEl=row.querySelector(".pred-lag");const lagVisible=lagEl&&lagEl.style.display!=="none";const lag=lagVisible?parseInt(lagEl.value,10)||0:0;let token=id+"#"+type;if(lag>0)token+="+"+lag;else if(lag<0)token+=lag;parts.push(token)}return parts.join(",")};App.addPredRow=function(){const list=document.getElementById("tf-pred-list");if(!list)return;list.insertAdjacentHTML("beforeend",App._predRowHtml(null,App._predCands||[]))};App.removePredRow=function(btn){const list=document.getElementById("tf-pred-list");const row=btn.closest(".pred-row");if(!list||!row)return;row.remove();if(!list.querySelector(".pred-row"))App.addPredRow()};App.onTaskStageChange=function(){const list=document.getElementById("tf-pred-list");if(!list)return;const newStage=(document.getElementById("tf-stage")||{}).value||"";const current=Array.from(list.querySelectorAll(".pred-row")).map(row=>{const sel=row.querySelector(".pred-search");const id=sel?(sel.value||"").trim():"";if(!id)return null;const type=(row.querySelector(".pred-rel")||{}).value||"FS";const lagEl=row.querySelector(".pred-lag");const lag=lagEl?parseInt(lagEl.value,10)||0:0;return{dep:id,type,lag}}).filter(Boolean);const cands=App.predCandidates(App._predProj,App._predSelfId,newStage,App._predVariant);App._predCands=cands;const inWindow=new Set(cands.map(c=>c.id));const kept=current.filter(p=>inWindow.has(p.dep));const dropped=current.length-kept.length;list.innerHTML=kept.length?kept.map(p=>App._predRowHtml(p,cands)).join(""):App._predRowHtml(null,cands);if(dropped>0){U.toast("⚠️"+dropped+" 筆前置因階段調整超出可選範圍，已移除","warning",{soft:true})}};
