/*! PM-Core (c) 2026 Paul Hsu. All Rights Reserved. Proprietary — see LICENSE. */
App.getTaskFilter=function(projId){this._taskFilter=this._taskFilter||{};if(!this._taskFilter[projId])this._taskFilter[projId]={stages:new Set,owners:new Set,urg:new Set,status:new Set};return this._taskFilter[projId]};App.taskOwnerOptions=function(projectId){const set=new Set;(DATA.tasks||[]).forEach(t=>{if(t.project===projectId&&!t._deleted&&typeof t.owner==="string"&&t.owner.trim())set.add(t.owner.trim())});return[...set].sort((a,b)=>a.localeCompare(b,"zh-Hant"))};App._npiVariantTabs=function(proj){const vs=proj.variants||[];return vs.length<2?null:vs};App._npiActiveVariant=function(proj){const vs=this._npiVariantTabs(proj);if(!vs)return null;this._npiVariantTab=this._npiVariantTab||{};const cur=this._npiVariantTab[proj.id];return cur&&vs.some(v=>v.id===cur)?cur:vs[0].id};App._npiVariantTabsHtml=function(proj){const vs=this._npiVariantTabs(proj);if(!vs)return"";const active=this._npiActiveVariant(proj);return'<div class="npi-vtabs">'+vs.map((v,i)=>'<button class="npi-vtab'+(v.id===active?" on":"")+`" onclick="App._npiSetVariantTab('`+proj.id+"', '"+v.id+`')">`+(i===0?'<i class="ti ti-star" aria-hidden="true"></i> 主案 · ':"")+U.esc(v.name||"案別"+(i+1))+"</button>").join("")+"</div>"};App._npiSetVariantTab=function(projId,vid){this._npiVariantTab=this._npiVariantTab||{};this._npiVariantTab[projId]=vid;this.renderProject()};App.buildTaskFilterBar=function(projId){const seenStage=new Set;const stageOpts=this.getProjectStages(projId).filter(s=>{if(seenStage.has(s.name))return false;seenStage.add(s.name);return true}).map(s=>({value:s.name,label:s.name}));const ownerOpts=this.taskOwnerOptions(projId).map(o=>({value:o,label:o}));const urgOpts=["high","medium","low"].map(v=>({value:v,label:URGENCY_LABELS_ZH[v]}));const statusOpts=["pending","wip","done","hold"].map(v=>({value:v,label:STATUS_LABELS_ZH[v]}));return`<div class="task-filter-bar">
    ${this.buildTaskFilterChip(projId,"stages","階段",stageOpts)}
    ${this.buildTaskFilterChip(projId,"owners","負責人",ownerOpts)}
    ${this.buildTaskFilterChip(projId,"urg","緊急程度",urgOpts)}
    ${this.buildTaskFilterChip(projId,"status","狀態",statusOpts)}
    <div class="tf-search"><i class="ti ti-search" aria-hidden="true"></i><input id="taskSearchInput" placeholder="搜尋任務…" value="${U.esc(this._taskSearch&&this._taskSearch[projId]||"")}" oninput="App.setTaskSearch('${projId}', this.value)"></div>
    <button class="tf-clear-all" onclick="App.clearTaskFilter('${projId}')">全部清除</button>
  </div>`};App.buildTaskFilterChip=function(projId,key,label,options){const sel=this.getTaskFilter(projId)[key];const selArr=[...sel];const chipText=selArr.length===0?label:selArr[0]+(selArr.length>1?` +${selArr.length-1}`:"");const boxes=options.length?options.map(o=>`<label class="tf-opt${sel.has(o.value)?" on":""}">
      <input type="checkbox" value="${U.esc(o.value)}"${sel.has(o.value)?" checked":""}
        onchange="App.toggleTaskFilterOpt('${projId}','${key}',this.value,this.checked)">
      <span>${U.esc(o.label)}</span>
    </label>`).join(""):'<div class="tf-empty">無選項</div>';return`<div class="tf-chip-wrap" data-key="${key}">
    <button class="tf-chip tf-${key}${selArr.length?" active":""}" data-label="${U.esc(label)}"
      onclick="App.toggleTaskFilterPanel('${projId}','${key}')">
      <span class="tf-chip-label">${U.esc(chipText)}</span><span class="tf-caret">▾</span>
    </button>
    <div class="tf-panel">
      <div class="tf-opts">${boxes}</div>
      <div class="tf-panel-foot">
        <button onclick="App.clearTaskFilterKey('${projId}','${key}')">清除</button>
        <button onclick="App.toggleTaskFilterPanel('${projId}','${key}')">套用</button>
      </div>
    </div>
  </div>`};App.toggleTaskFilterPanel=function(projId,key){const wrap=document.querySelector(`.tf-chip-wrap[data-key="${key}"]`);if(!wrap)return;const willOpen=!wrap.classList.contains("open");document.querySelectorAll(".tf-chip-wrap.open").forEach(w=>w.classList.remove("open"));if(willOpen)wrap.classList.add("open");else this.renderProject()};App.toggleTaskFilterOpt=function(projId,key,value,checked){const sel=this.getTaskFilter(projId)[key];checked?sel.add(value):sel.delete(value);const wrap=document.querySelector(`.tf-chip-wrap[data-key="${key}"]`);if(!wrap)return;wrap.querySelectorAll(".tf-opt").forEach(l=>l.classList.toggle("on",l.querySelector("input").checked));const chip=wrap.querySelector(".tf-chip");const selArr=[...sel];chip.classList.toggle("active",selArr.length>0);wrap.querySelector(".tf-chip-label").textContent=selArr.length===0?chip.dataset.label:selArr[0]+(selArr.length>1?` +${selArr.length-1}`:"")};App.clearTaskFilterKey=function(projId,key){this.getTaskFilter(projId)[key].clear();const wrap=document.querySelector(`.tf-chip-wrap[data-key="${key}"]`);if(wrap)wrap.querySelectorAll("input[type=checkbox]").forEach(cb=>{cb.checked=false;cb.dispatchEvent(new Event("change"))});this.renderProject()};App.clearTaskFilter=function(projId){const f=this.getTaskFilter(projId);["stages","owners","urg","status"].forEach(k=>f[k].clear());if(this._taskSearch)this._taskSearch[projId]="";document.querySelectorAll(".task-filter-bar input[type=checkbox]").forEach(cb=>{cb.checked=false;cb.dispatchEvent(new Event("change"))});this.renderProject()};App.setTaskSearch=function(projId,val){this._taskSearch=this._taskSearch||{};this._taskSearch[projId]=val;this.renderProject();const el=document.getElementById("taskSearchInput");if(el){el.focus();const n=el.value.length;if(el.setSelectionRange)el.setSelectionRange(n,n)}};
